name: Laravel CI

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, iconv
          ini-file: production
      - name: Install dependencies
        working-directory: backend
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run Pint
        working-directory: backend
        run: ./vendor/bin/pint --test


  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: notifications_test
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U laravel"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7

      rabbitmq:
        image: rabbitmq:3-management

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, iconv, pdo_pgsql, redis
          ini-file: production

      - name: Install dependencies
        working-directory: backend
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare environment
        working-directory: backend
        run: |
          cp .env.testing.example .env
          php artisan key:generate

      - name: Run migrations
        working-directory: backend
        env:
          APP_ENV: testing
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: notifications_test
          DB_USERNAME: laravel
          DB_PASSWORD: testing
        run: php artisan migrate --force

      - name: Run tests
        working-directory: backend
        env:
          APP_ENV: testing
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: notifications_test
          DB_USERNAME: laravel
          DB_PASSWORD: testing
        run: php artisan test